title: Андрей Крисанов
author: Андрей Крисанов
description: Заметки o разработке и менеджменте

repository: akrisanov/akrisanov.github.io
url: https://akrisanov.ru
baseurl: ""
permalink: /:year/:month/:day/:slug/
paginate: 5
lang: ru
date_format: "%d.%m.%Y"

# Layout

show_excerpts: true # show article excerpts on the home page
show_frame: true # adds a gray frame to the site
show_sidebar: false # show a sidebar instead of the usual header
minimal: false # use a dark header

# Menu

navigation: # accepts {file, title, url, icon, sidebaricon}
  - { title: "Обо мне", file: "about.md" }
  - { title: "Заметки", icon: "home", file: "index.html" }

external: # shows a footer with social links - for available icons see fontawesome.com/icons
  - {
      title: Контакты,
      icon: "address-card",
      url: "https://linktr.ee/akrisanov",
    }
  - {
      title: Linkedin,
      icon: linkedin,
      url: "https://linkedin.com/in/akrisanov/",
    }
  - { title: Github, icon: github, url: "https://github.com/akrisanov/" }
  - { title: RSS, icon: rss, url: "/feed.xml" }

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-youtube
  - jekyll-twitter-plugin
  - jekyll-gist
  - months

safe: false
