on:
  push:
    branches: [master]
name: Build and deploy on Github Pages
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          # TOKEN: ${{ secrets.GITHUB_TOKEN }}
